name: Run Cucumber Tests Locally

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip

   - name: Install Dependencies
  run: |
    sudo apt-get update
    sudo apt-get install -y wget unzip
    CHROME_VERSION=$(google-chrome --version | sed 's/Google Chrome \(.*\)\..*/\1/')
    DRIVER_VERSION=$(wget -qO- "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}")
    wget "https://chromedriver.storage.googleapis.com/${DRIVER_VERSION}/chromedriver_linux64.zip"
    unzip chromedriver_linux64.zip
    sudo mv chromedriver /usr/local/bin/


      - name: Run Cucumber tests with Maven
        run: mvn clean test
        env:
          SELENIDE_URL: "https://www.demoblaze.com/"
