name: Run Cucumber Tests Locally

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://chromedriver.storage.googleapis.com/133.0.6943.142/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/

      - name: Run Cucumber tests with Maven
        run: mvn clean test
        env:
          SELENIDE_URL: "https://www.demoblaze.com/"
          # Here you can set additional environment variables to customize the behavior
