name: Run Cucumber Tests Locally

on:
  push:
    branches:
      - master  # Используем ветку master
  pull_request:
    branches:
      - master  # Используем ветку master
  workflow_dispatch:  # Добавлено для ручного запуска

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Clean project with Maven
        run: mvn clean  # Добавляем команду для очистки проекта перед сборкой

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl unzip
          # Устанавливаем Google Chrome
          sudo apt-get install -y google-chrome-stable

      - name: Install WebDriverManager via Maven
        run: |
          curl -sS https://get.sdkman.io | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install maven
          mvn dependency:get -Dartifact=com.github.webdriverextensions:webdriverextensions:2.0.0
          mvn dependency:get -Dartifact=io.github.bonigarcia:webdrivermanager:5.3.0

      - name: Install ChromeDriver with WebDriverManager
        run: |
          mvn exec:exec -Dexec.executable="java" -Dexec.args="-cp target/classes:target/dependency/* io.github.bonigarcia.webdrivermanager.WebDriverManager chrome"

      - name: Verify Google Chrome Installation
        run: |
          google-chrome --version || { echo "Google Chrome is not installed"; exit 1; }

      - name: Verify ChromeDriver Installation
        run: |
          chromedriver --version || { echo "ChromeDriver is not installed"; exit 1; }

      - name: Run Cucumber tests with Maven
        run: mvn clean test  # Запуск тестов после очистки проекта
        env:
          SELENIDE_URL: "https://www.demoblaze.com/"  # URL для тестов
          DISPLAY: ":99"  # Для запуска безголового режима на CI
          
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-test-results
          path: target/cucumber-reports  # Путь к отчетам Cucumber, если вы используете maven-cucumber-reporting
