name: Run Cucumber Tests

on:
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  test:
    runs-on: ubuntu-latest  # Используется виртуальная машина с Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Проверка кода

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://chromedriver.storage.googleapis.com/133.0.6943.142/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/  # Устанавливаем ChromeDriver

      - name: Run Cucumber tests with Maven
        run: mvn clean test  # Запуск тестов через Maven
        env:
          SELENIDE_URL: "https://www.demoblaze.com/"  # URL для тестов
