name: Run Cucumber Tests Locally

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Добавлено для ручного запуска

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Verify ChromeDriver and Google Chrome Installation
        run: |
          # Проверка, что Google Chrome установлен
          google-chrome --version || { echo "Google Chrome is not installed"; exit 1; }
          
          # Проверка, что chromedriver установлен
          chromedriver --version || { echo "ChromeDriver is not installed"; exit 1; }

      - name: Run Cucumber tests with Maven
        run: mvn clean test
        env:
          SELENIDE_URL: "https://www.demoblaze.com/"
          SELENIDE_CHROME_OPTIONS: |
            --headless
            --no-sandbox
            --disable-dev-shm-usage
            --window-size=1920x1080
            --user-data-dir=/tmp/chrome-data-dir  # Ensure a unique user data dir for each test
          # If using additional environment variables specific to your tests
          # Add them here
