name: Run Cucumber Tests Locally

on:
  push:
    branches:
      - master  # Используем ветку master
  pull_request:
    branches:
      - master  # Используем ветку master
  workflow_dispatch:  # Добавлено для ручного запуска

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl unzip
          
          # Устанавливаем Google Chrome
          sudo apt-get install -y google-chrome-stable
          
          # Устанавливаем ChromeDriver через WebDriverManager (если не был установлен ранее)
          curl -sS https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip -o chromedriver.zip
          unzip chromedriver.zip
          sudo mv chromedriver /usr/local/bin
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Verify ChromeDriver and Google Chrome Installation
        run: |
          # Проверяем, что Google Chrome установлен
          google-chrome --version || { echo "Google Chrome is not installed"; exit 1; }

          # Проверяем, что ChromeDriver установлен
          chromedriver --version || { echo "ChromeDriver is not installed"; exit 1; }

      - name: Run Cucumber tests with Maven
        run: mvn clean test
        env:
          SELENIDE_URL: "https://www.demoblaze.com/"
