name: Run Cucumber Tests Manually

on:
  workflow_dispatch:  # Позволяет запускать тесты вручную

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository  # Кеширование зависимостей Maven для ускорения сборки
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies
        run: mvn install -DskipTests  # Устанавливаем зависимости без выполнения тестов

      - name: Run Cucumber tests with Maven
        run: mvn test  # Запуск тестов
