name: Run Cucumber Tests Locally

on:
  push:
    branches:
      - master  # Используем ветку master
  pull_request:
    branches:
      - master  # Используем ветку master
  workflow_dispatch:  # Добавлено для ручного запуска

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl unzip

          # Устанавливаем Google Chrome
          sudo apt-get install -y google-chrome-stable

          # Получаем текущую версию Google Chrome
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          echo "Detected Chrome version: $CHROME_VERSION"

          # Получаем основную версию Chrome (например, 114 из 114.0.5735.90)
          CHROME_MAJOR_VERSION=$(echo $CHROME_VERSION | cut -d'.' -f1)
          echo "Detected Chrome major version: $CHROME_MAJOR_VERSION"

          # Устанавливаем соответствующую версию ChromeDriver через WebDriverManager
          # Вместо использования LATEST_RELEASE_ ... используем корректный способ
          CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE | awk -F= '{print $2}')
          echo "Detected ChromeDriver version: $CHROMEDRIVER_VERSION"

          curl -sS https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip -o chromedriver.zip
          unzip chromedriver.zip
          sudo mv chromedriver /usr/local/bin
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Verify ChromeDriver and Google Chrome Installation
        run: |
          # Проверяем, что Google Chrome установлен
          google-chrome --version || { echo "Google Chrome is not installed"; exit 1; }
          # Проверяем, что ChromeDriver установлен
          chromedriver --version || { echo "ChromeDriver is not installed"; exit 1; }

      - name: Run Cucumber tests with Maven
        run: mvn clean test
        env:
          SELENIDE_URL: "https://www.demoblaze.com/"
