name: Run Cucumber Tests Manually

on:
  workflow_dispatch:  # Позволяет запускать тесты вручную

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Clean previous build
        run: mvn clean  # Очистка предыдущих артефактов сборки

      - name: Run Cucumber tests with Maven
        run: mvn test  # Запуск тестов
