name: Run Cucumber Tests Locally

on:
  push:
    branches:
      - master  # Используем ветку master
  pull_request:
    branches:
      - master  # Используем ветку master
  workflow_dispatch:  # Добавлено для ручного запуска

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl unzip

          # Устанавливаем Google Chrome
          sudo apt-get install -y google-chrome-stable

      - name: Set up WebDriverManager for ChromeDriver
        run: |
          # Устанавливаем WebDriverManager
          curl -sSL https://github.com/bonigarcia/webdrivermanager/releases/download/v5.3.0/webdrivermanager-5.3.0.jar -o webdrivermanager.jar
          # Запускаем WebDriverManager для установки нужной версии ChromeDriver
          java -jar webdrivermanager.jar chrome

      - name: Verify ChromeDriver and Google Chrome Installation
        run: |
          # Проверяем, что Google Chrome установлен
          google-chrome --version || { echo "Google Chrome is not installed"; exit 1; }
          # Проверяем, что ChromeDriver установлен
          chromedriver --version || { echo "ChromeDriver is not installed"; exit 1; }

      - name: Run Cucumber tests with Maven
        run: mvn clean test
        env:
          SELENIDE_URL: "https://www.demoblaze.com/"
